---
jira:
  # url: https://issues.redhat.com
  project-id: RHTAP
comments:
  footer: >
    {color:#505f79}See also
    [rhtap.yaml|https://github.com/konflux-ci/prioritize/blob/main/config/rhtap.yaml],
    the [source code|https://github.com/konflux-ci/prioritize], and the
    [runner|https://gitlab.cee.redhat.com/rbean/jira-automation/-/blob/main/.gitlab-ci.yml]
    for this bot.{color}
program_automation:
  issues:
    Feature:
      # collector: get_issues
      rules:
        - check_target_end_date
    Outcome:
      # collector: get_issues
      rules:
        - check_components
team_automation:
  issues:
    Feature:
      # collector: get_issues
      group_rules:
        - rule: check_rank_with_order_by
          kwargs:
            order_by: fixVersion, priority, component
            cascade: true
    Epic:
      collector: get_child_issues
      rules:
        - check_due_date
