---
jira:
  # url: https://issues.redhat.com
  project-id:  # PROJECT_KEY
team_automation:
  issues:
    Epic:
      # collector: get_issues
      rules:
        - check_parent_link
        - check_priority
        - check_due_date
        - check_target_dates
        - set_fix_version
      group_rules:
        - check_rank
    Story:
      # collector: get_issues
      rules:
        - check_parent_link
        - check_priority
        - check_quarter_label
        - check_due_date
      group_rules:
        - check_rank
